# IMAGENES PROGRAMA
ruta_logo_programa          = 'imagenes/cuadrado.png'
ruta_imagen_instrucciones   = 'imagenes/instrucciones.png'
# COLORES PROGRAMA
color_menu_superior         = 'black' #1 '#1f2329'
color_menu_lateral          = '#2a3138'
color_cuerpo                = '#f1faff'
color_menu_cursor_encima    = '#2f88c5'
color_login_borde           = '#2C3E50'
color_login_relleno         = '#2C3E50'
# DATOS EMPRESA
nombreCompleto              = 'DOMINGO MARCHAN DEL PINO'
empresa                     = 'CIFO La Violeta'
mail_empresa                = 'julandron@hotmail.com'
ruta_logo_empresa           = 'imagenes/logo_empresa.png'
calleEmpresa                = 'C/ INVENTADA, 8'
poblacionEmpresa            = 'BARCELONA'
cpProvinciaEmpresa          = '00000 BARCELONA'
telEmpresa                  = 'Tel.: +xx  XXXXXXXXX'
dniCifEmpresa               = 'XXXXXXXX - A'
correoEmpresa               = 'mailinventado@gmail.com'
formaPago                   = 'Contado'
bancoPagar                  = 'La Caixa'
iban                        = 'ES ................'